### PR TITLE
Hello-React-Rails

### PR DESCRIPTION
**Pull request by Fatima-hub333**
### The following tasks are implemented in this PR;

- [ ] Create a new Rails app called 'hello-rails-react'.
- Use tcommandend rails new -j webpack my_new_rails_app as described in the previous lesson's tutorial.

- [ ] Verify that the jsbundling-rails gem is added to your Gemfile.
- [ ] Initialize your project with Git.
- [ ] Install needed node dependencies as described in the previous lesson's tutorial.
- [ ] Create a babel.config.js in the root folder of your project as described in the previous lesson's tutorial.
- [ ] Update webpack.config.js to include the babel-loader as described in the previous lesson's tutorial.
- [ ] Make sure that your project has a Postgres database set up.
- [ ] Create a table for storing your messages and create 5 different greetings.
- [ ] Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
- [ ] Create a static view that will be the root of your app.
- [ ] Create the App component with react-router and render it in your static view.
- [ ] Create the Greeting component that will display a greeting. Set it up as a route in your App component.
- [ ] Create a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
- [ ] Display the random greeting in your Greeting component.

## Thanks for taking out the time to review this project 🧨
It really is appreciated :) ❤️ 
- Note: I personally love optional suggestions so please do leave some 😄

### CODE REVIEW

**Review by CollinsTatang — CHANGES_REQUESTED** [review]
Hi @Fatima-hub333 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, without a professional README file 

- [ ] Please README file should be descriptive
- all main headers from the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) should be present in the repo. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by smunozmo — CHANGES_REQUESTED** [review]
Hi @Fatima-hub333, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!


## Required Changes ♻️

Screen Shot 2022-09-19 at 1 31 06 PM

- [ ] Your code is looking good, excellent job! However, for some reason I was not able to run webpack, if there's any additional configuration or installation please add it to the README file, or let me know if this is an error from my local machine. 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Fatima-hub333** [comment]
Thank you for reaching out to me. It's working fine from my end. Can you
recheck on your side plz?
Also there are no installation other than those which I mentioned in
README.md

**Comment by smunozmo** [comment]
Hi @Fatima-hub333, sure!
please submit it again for review. 🚀

**Review by tufoinnkuo10 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @Fatima-hub333 

Your project is complete! Great job  🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Random Greetings Rendered
- All files available
- Required gems available
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
